# Generated by Django 3.2.3 on 2023-10-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_registro', models.CharField(max_length=10)),
                ('fecha_ingreso', models.DateField(default=None)),
                ('fecha_sintomas', models.DateField(default=None)),
                ('edad', models.IntegerField()),
                ('pais_nacimiento', models.CharField(max_length=50)),
            ],
        ),
    ]
